---
- block: # Enable kernel module

  - name: Enable ip_vs in module file
    lineinfile:
      dest: /etc/modules
      regexp: '^ip_vs$'
      line: ip_vs
    become: true

  - name: Enable ip_vs module
    modprobe:
      name: ip_vs
      state: present
    become: true

- block: # Copy Keepalived configuration file

  - name: Create a random virtual router id
    set_fact:
      keepalived_vri: "{{ 255 | random() }}"
    run_once: true
    delegate_to: 127.0.0.1
    when: keepalived_vri is not defined

  - name: Copy Keepalived configuration file to container
    template:
      src: "{{ keepalived_template_file }}"
      dest: "{{ keepalived_container_config_path }}"
    notify: Restart Keepalived service
