---
- name: Add Keepalived PPA repository
  apt_repository:
    repo: ppa:keepalived/daily
    update_cache: yes

- name: Install Keepalived
  apt:
     pkg: "{{ keepalived_service_name }}"
     state: latest
     update_cache: no
